# Generated by Django 3.2.8 on 2021-10-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayscounter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Days',
            new_name='Day',
        ),
    ]
