# Generated by Django 3.2.8 on 2021-10-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayscounter', '0002_rename_days_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='day',
            name='day_start',
            field=models.DateField(),
        ),
    ]
